// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plus5.Infrastructure.Persistence;

#nullable disable

namespace Plus5.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Plus5DbContext))]
    [Migration("20260901224924_AddStudentEditingConcurrency")]
    partial class AddStudentEditingConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Plus5.Domain.Groups.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SchoolGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TeacherAccountId", "Id")
                        .HasName("AK_Groups_Teacher_Id");

                    b.HasIndex("SchoolGradeId")
                        .HasDatabaseName("IX_Groups_SchoolGradeId");

                    b.HasIndex("TeacherAccountId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Groups_Teacher_NormalizedName");

                    b.HasIndex("TeacherAccountId", "ProgramId")
                        .HasDatabaseName("IX_Groups_Teacher_ProgramId");

                    b.HasIndex("TeacherAccountId", "ArchivedAtUtc", "Status")
                        .HasDatabaseName("IX_Groups_Teacher_Archived_Status");

                    b.ToTable("Groups", null, t =>
                        {
                            t.HasCheckConstraint("CK_Groups_ArchivedStatus", "[ArchivedAtUtc] IS NULL OR [Status] = 3");

                            t.HasCheckConstraint("CK_Groups_Capacity", "[Capacity] > 0");

                            t.HasCheckConstraint("CK_Groups_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Groups.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_GroupMemberships_Student_Active")
                        .HasFilter("[LeftAtUtc] IS NULL");

                    b.HasIndex("GroupId", "LeftAtUtc")
                        .HasDatabaseName("IX_GroupMemberships_Group_LeftAtUtc");

                    b.HasIndex("TeacherAccountId", "GroupId");

                    b.HasIndex("TeacherAccountId", "StudentId");

                    b.HasIndex("GroupId", "StudentId", "JoinedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_GroupMemberships_Group_Student_JoinedAtUtc");

                    b.ToTable("GroupMemberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupMemberships_Validity", "[LeftAtUtc] IS NULL OR [LeftAtUtc] >= [JoinedAtUtc]");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Identity.AccountToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_AccountTokens_TokenHash");

                    b.HasIndex("UserAccountId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("UX_AccountTokens_ActivePurpose")
                        .HasFilter("[ConsumedAtUtc] IS NULL");

                    b.HasIndex("UserAccountId", "Purpose", "ExpiresAtUtc")
                        .HasDatabaseName("IX_AccountTokens_Account_Purpose_Expiry");

                    b.ToTable("AccountTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountTokens_Purpose", "[Purpose] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Identity.AuthenticatedSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "ExpiresAtUtc")
                        .HasDatabaseName("IX_AuthenticatedSessions_Account_Expiry");

                    b.ToTable("AuthenticatedSessions", (string)null);
                });

            modelBuilder.Entity("Plus5.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAccounts_NormalizedEmail");

                    b.ToTable("UserAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAccounts_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Scheduling.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TeacherAccountId", "Id")
                        .HasName("AK_Locations_Teacher_Id");

                    b.HasIndex("TeacherAccountId", "ArchivedAtUtc")
                        .HasDatabaseName("IX_Locations_Teacher_Archived");

                    b.HasIndex("TeacherAccountId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Locations_Teacher_NormalizedName");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Plus5.Domain.Scheduling.RecurringSessionSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("LocalEndTime")
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("LocalStartTime")
                        .HasColumnType("time(0)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OnlineMeetingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("PreviousSeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TeacherAccountId", "Id")
                        .HasName("AK_RecurringSessionSeries_Teacher_Id");

                    b.HasIndex("PreviousSeriesId")
                        .IsUnique()
                        .HasDatabaseName("UX_RecurringSessionSeries_PreviousSeriesId")
                        .HasFilter("[PreviousSeriesId] IS NOT NULL");

                    b.HasIndex("TeacherAccountId", "LocationId");

                    b.HasIndex("TeacherAccountId", "PreviousSeriesId");

                    b.HasIndex("TeacherAccountId", "GroupId", "SupersededAtUtc", "DayOfWeek")
                        .HasDatabaseName("IX_RecurringSessionSeries_Group_Active_Day");

                    b.HasIndex("TeacherAccountId", "StudentId", "SupersededAtUtc", "DayOfWeek")
                        .HasDatabaseName("IX_RecurringSessionSeries_Student_Active_Day");

                    b.ToTable("RecurringSessionSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringSessionSeries_Context", "([Kind] = 1 AND [GroupId] IS NOT NULL AND [StudentId] IS NULL) OR ([Kind] = 2 AND [GroupId] IS NULL AND [StudentId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_RecurringSessionSeries_DateRange", "[EndsOn] >= [StartsOn]");

                            t.HasCheckConstraint("CK_RecurringSessionSeries_DayOfWeek", "[DayOfWeek] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_RecurringSessionSeries_Kind", "[Kind] IN (1, 2)");

                            t.HasCheckConstraint("CK_RecurringSessionSeries_Location", "[LocationId] IS NULL OR [OnlineMeetingUrl] IS NULL");

                            t.HasCheckConstraint("CK_RecurringSessionSeries_Previous", "[PreviousSeriesId] IS NULL OR [PreviousSeriesId] <> [Id]");

                            t.HasCheckConstraint("CK_RecurringSessionSeries_TimeRange", "[LocalEndTime] > [LocalStartTime]");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Scheduling.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSeriesException")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OnlineMeetingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("RecurringSessionSeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("SeriesOccurrenceDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("RecurringSessionSeriesId", "SeriesOccurrenceDate")
                        .IsUnique()
                        .HasDatabaseName("UX_Sessions_Series_Occurrence")
                        .HasFilter("[RecurringSessionSeriesId] IS NOT NULL");

                    b.HasIndex("TeacherAccountId", "RecurringSessionSeriesId");

                    b.HasIndex("TeacherAccountId", "GroupId", "StartsAtUtc")
                        .HasDatabaseName("IX_Sessions_Group_Start")
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.HasIndex("TeacherAccountId", "StudentId", "StartsAtUtc")
                        .HasDatabaseName("IX_Sessions_Student_Start")
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.HasIndex("TeacherAccountId", "StartsAtUtc", "EndsAtUtc", "Status")
                        .HasDatabaseName("IX_Sessions_Teacher_Time_Status");

                    b.HasIndex("TeacherAccountId", "LocationId", "StartsAtUtc", "EndsAtUtc", "Status")
                        .HasDatabaseName("IX_Sessions_Location_Time_Status")
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.ToTable("Sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sessions_Cancellation", "([Status] = 4 AND [CancelledAtUtc] IS NOT NULL) OR ([Status] <> 4 AND [CancelledAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_Sessions_Context", "([DeliveryMode] = 1 AND [StudentId] IS NOT NULL AND [GroupId] IS NULL) OR ([DeliveryMode] = 2 AND [StudentId] IS NULL AND [GroupId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Sessions_DeliveryMode", "[DeliveryMode] IN (1, 2)");

                            t.HasCheckConstraint("CK_Sessions_Location", "[LocationId] IS NULL OR [OnlineMeetingUrl] IS NULL");

                            t.HasCheckConstraint("CK_Sessions_SeriesOccurrence", "([RecurringSessionSeriesId] IS NULL AND [SeriesOccurrenceDate] IS NULL) OR ([RecurringSessionSeriesId] IS NOT NULL AND [SeriesOccurrenceDate] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Sessions_Status", "[Status] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Sessions_TimeRange", "[EndsAtUtc] > [StartsAtUtc]");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Students.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Guardians_Student_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("StudentId", "IsPrimary")
                        .HasDatabaseName("IX_Guardians_Student_Primary");

                    b.ToTable("Guardians", (string)null);
                });

            modelBuilder.Entity("Plus5.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DeliveryMode")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SchoolGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TeacherAccountId", "Id")
                        .HasName("AK_Students_Teacher_Id");

                    b.HasIndex("SchoolGradeId")
                        .HasDatabaseName("IX_Students_SchoolGradeId");

                    b.HasIndex("TeacherAccountId", "ProgramId")
                        .HasDatabaseName("IX_Students_Teacher_ProgramId");

                    b.HasIndex("TeacherAccountId", "ArchivedAtUtc", "Status")
                        .HasDatabaseName("IX_Students_Teacher_Archived_Status");

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Students_ArchivedStatus", "[ArchivedAtUtc] IS NULL OR [Status] = 3");

                            t.HasCheckConstraint("CK_Students_DeliveryMode", "[DeliveryMode] IS NULL OR [DeliveryMode] IN (1, 2)");

                            t.HasCheckConstraint("CK_Students_Organization", "([ProgramId] IS NULL AND [DeliveryMode] IS NULL) OR ([ProgramId] IS NOT NULL AND [DeliveryMode] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Students_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Teaching.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_Curricula_Code_Version");

                    b.ToTable("Curricula", (string)null);
                });

            modelBuilder.Entity("Plus5.Domain.Teaching.ProficiencyLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FrameworkCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkCode", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ProficiencyLevels_Framework_Code");

                    b.HasIndex("FrameworkCode", "SortOrder")
                        .HasDatabaseName("IX_ProficiencyLevels_Framework_SortOrder");

                    b.ToTable("ProficiencyLevels", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProficiencyLevels_SortOrder", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Teaching.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("TeacherAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TeacherAccountId", "Id")
                        .HasName("AK_Programs_Teacher_Id");

                    b.HasIndex("TeacherAccountId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Programs_Teacher_NormalizedName");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("Plus5.Domain.Teaching.SchoolGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_SchoolGrades_Code");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_SchoolGrades_SortOrder");

                    b.ToTable("SchoolGrades", null, t =>
                        {
                            t.HasCheckConstraint("CK_SchoolGrades_SortOrder", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("Plus5.Domain.Groups.Group", b =>
                {
                    b.HasOne("Plus5.Domain.Teaching.SchoolGrade", null)
                        .WithMany()
                        .HasForeignKey("SchoolGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plus5.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plus5.Domain.Teaching.Program", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "ProgramId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Plus5.Domain.Groups.GroupMembership", b =>
                {
                    b.HasOne("Plus5.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "GroupId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plus5.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "StudentId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Plus5.Domain.Identity.AccountToken", b =>
                {
                    b.HasOne("Plus5.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Plus5.Domain.Identity.AuthenticatedSession", b =>
                {
                    b.HasOne("Plus5.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Plus5.Domain.Scheduling.Location", b =>
                {
                    b.HasOne("Plus5.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Plus5.Domain.Scheduling.RecurringSessionSeries", b =>
                {
                    b.HasOne("Plus5.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plus5.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "GroupId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plus5.Domain.Scheduling.Location", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "LocationId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plus5.Domain.Scheduling.RecurringSessionSeries", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "PreviousSeriesId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plus5.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "StudentId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Plus5.Domain.Scheduling.Session", b =>
                {
                    b.HasOne("Plus5.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plus5.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "GroupId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plus5.Domain.Scheduling.Location", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "LocationId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plus5.Domain.Scheduling.RecurringSessionSeries", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "RecurringSessionSeriesId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plus5.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "StudentId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Plus5.Domain.Students.Guardian", b =>
                {
                    b.HasOne("Plus5.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Plus5.Domain.Students.Student", b =>
                {
                    b.HasOne("Plus5.Domain.Teaching.SchoolGrade", null)
                        .WithMany()
                        .HasForeignKey("SchoolGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plus5.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plus5.Domain.Teaching.Program", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId", "ProgramId")
                        .HasPrincipalKey("TeacherAccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Plus5.Domain.Teaching.Program", b =>
                {
                    b.HasOne("Plus5.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
